# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('drink_preference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_loser', to='datastore.Player')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_players', to='datastore.Player')),
            ],
        ),
    ]
