# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mug_clean', models.BooleanField()),
                ('drink_type', models.CharField(choices=[('Tea', 'tea'), ('Coffee', 'coffee')], default='NA', max_length=20)),
                ('milk', models.BooleanField()),
                ('sugar', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='drink_preference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastore.DrinkRequirements'),
        ),
    ]
