# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_auto_20170518_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='players',
        ),
        migrations.AlterField(
            model_name='round',
            name='loser',
            field=models.CharField(max_length=100),
        ),
    ]
